### ISSUE TITLE
calibration, strength of magnetic field

### ISSUE THREAD

**Issue by paulle** [Kr0oked/Compass#1]
First thank you for the nice compass.
Maybe it would be nice to have an option for calibrating and an option to see the strength of the field (Tesla).

**Comment by Kr0oked** [comment]
Hi, thanks for the suggestions.
These are two features I also considered. But I was not sure if they are really usefull ones.
To be honest, when other compass apps showed me the magnetic field strength I didn't know what to do with that. I would love to know if you have different experiences.
For the calibration I want to add a notice that suggests doing the 8 figure. But on all my test devices the sensor accuracy of both the accelerometer and magnetometer never changed. So I would also like to know if you ever had to calibrate your magnetometer.

**Comment by paulle** [comment]
A hint popping for calibration would be fine. Showing the strength of magnetic field you are it's mostly the same, but it gives a good control if you are near other magnetic sources, which disturb the the compass showing wrong directions, in this case it's very useful.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by Kr0oked** [comment]
I added a hint for calibration :+1: . I will probably skip the magnetic field strength and bubble to keep the compass simple, since I dont want to extend this app to a toolbox.

**Comment by paulle** [comment]
I understand that you want to keep the app simple, but I don't see the toolbox when one can the magnetic field strength for looking of there are maybe other sources of magnetic fields disturbing the correct work of the compass and a bubble has every 'physical' compass too.

But with it or without it it's a nice compass. Thank you for your work.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by primarto** [comment]
I will follow up here even though it is closed.

In the calibration guide you can put images below the text, calibration can be done in two ways.

Here is a picture as an example for you to understand me.

![Pic1](https://user-images.githubusercontent.com/62907157/115973776-e0f7b500-a557-11eb-99fc-15bf9c060b8d.jpg)
![Pic2](https://user-images.githubusercontent.com/62907157/115973779-e5bc6900-a557-11eb-998f-0b246b029a85.jpg)


Thank you for your work, very good compass app.
