### ISSUE TITLE
Mastodon account for this account

### ISSUE THREAD

**Issue by Lukas2112** [Kr0oked/Compass#10]
Would a Mastodon account for this project be possible?

**Comment by Kr0oked** [comment]
Are you talking about the blogging service? This project is currently in a finalized state and hasnt much community actitivity so I dont see a benefit in having a blogging account for it

**Comment by Lukas2112** [comment]
Yes. A use case could be if there were problems with an F-Droid version, you could communicate it through a Mastodon account.

**Comment by Kr0oked** [comment]
For the moment I will not start to add social media accounts for this app.
