### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by JM480** [Kr0oked/Compass#11]
Can you add support for Linux and Linux mobile devices like the Pinephone Pro? https://www.pine64.org/pinephonepro/

**Comment by Kr0oked** [comment]
I don't know a technique that allows Android Apps to support Linux distros. To use an Android app on a mobile Linux distro you have to use an Android emulator like [Anbox](https://anbox.io/). But of cause the best way would be to write a new native app for a distro but this is out of this projects scope.
