### ISSUE TITLE
wrong direction to the north if you flip the phone

### ISSUE THREAD

**Issue by OmlineEditor** [Kr0oked/Compass#17]
I was on the train, lying on my back and the phone was upside down, i.e. the screen was down to the ground. when I started the compass, the direction was shown the opposite, 180 degrees. the program does not take into account the flip of the screen down. please fix the bug.

**Comment by Kr0oked** [comment]
Thanks for reporting this issue. I corrected the behaviour and now the app shows the correct bearing in all screen orientations and also when the screen is flipped upside down.
This fix and your russian translations are available in the new release that should be available on the platforms in the next days.
Thank you again very much!
