### ISSUE TITLE
App crashes when opening "About the app" 2 times

### ISSUE THREAD

**Issue by Janokisu** [Kr0oked/Compass#19]
As the title says.

Version: 1.5

**Comment by Kr0oked** [comment]
Hello Janokisu, can you give me some information about your device and Android version?
Of cause it would be the best if you checkout the source code with Android Studio. Then you can compile the app yourself and let it run on your device and see a stracktrace in the console that describes what excatly went wrong.

**Comment by Janokisu** [comment]
It also crashes in the Android simulator. It doesn't do that for you?

**Comment by Janokisu** [comment]
It works. 👍
