### ISSUE TITLE
display strength of magnetical field

### ISSUE THREAD

**Issue by paulle** [Kr0oked/Compass#20]
Please can you add the strength of magnetical field. It would be useful in case there are other magnetical fields disturbing
the compass correctly showing north.

**Comment by Kr0oked** [comment]
Hi Paulle, thanks for your suggestion. But I decided to not display the magnetic field values. My experience is that these values do not help ordinary users to detect a disturbance of their compass. I will keep showing the accuracy that the devices sensor is reporting to the app as indicator.
