### ISSUE TITLE
180° remapping does not work properly

### ISSUE THREAD

**Issue by cramptonism** [Kr0oked/Compass#22]
I believe the X / Y values are swapped on this line:
https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/util/MathUtils.kt#L53

I was testing 180° remapping and North was in the wrong spot. Swapping these corrected it, and aligns with other implementations:
https://stackoverflow.com/questions/18782829/android-sensormanager-strange-how-to-remapcoordinatesystem

For testing the only way I was able to get into 180° was to start navigating in Google Maps and gesture-nav over to the compass. It's very clunky but unfortunately there does not appear to be a simple way to enable 180° rotations in settings/adb.

**Comment by Kr0oked** [comment]
@cramptonism Thanks for reporting this issue. You were absolutely right about the incorrect remapping. I would have never found this bug because as you said there is no simple way to test 180° screen rotation. Thank you very much!
