### ISSUE TITLE
Remove action bar

### ISSUE THREAD

**Issue by xmha97** [Kr0oked/Compass#26]
Hi, please remove action bar to display the compass larger.
![IMG_20221201_001252_135.jpg](https://user-images.githubusercontent.com/23485114/204914971-2dc3ef60-4c66-433e-aa63-38a170511241.jpg)

**Comment by Kr0oked** [comment]
Hello, I acknowledge that the compass appears too small in landscape mode. I will fix this issue by allowing the compass to reach into the top bar in landscape mode.

**Comment by xmha97** [comment]
Thanks.

**Comment by xmha97** [comment]
It used to be a larger compass in landscape mode and even stretched over the action bar, but now it doesn't.

![Screenshot_2023-11-05-22-33-52-437_com.bobek.compass.jpg](https://github.com/Kr0oked/Compass/assets/23485114/0a895dfe-88d2-4a5b-bcc6-0268aff31d74)
