### ISSUE TITLE
Jiggle and (relatively) slow response of heading

### ISSUE THREAD

**Issue by MrZMN** [Kr0oked/Compass#30]
Wonderful work! Thank you for providing such a remarkable compass application!

I've noticed two issues that may be further improved:

- **Jiggle of the heading**. When using the compass, sometimes the heading jiggles a bit. For example, even if I put the phone on a flat, stationary table, the heading sometimes changes for a few degrees (and may return back or not). Please kindly see [https://1drv.ms/v/s!AtC6mR0eG_AMav19bMorYzsFWoo?e=MwsHo3](url) as a short video that shows the issue.
- **Slow response of the heading**. Sometimes it takes a while for the heading to be stable (even if the sensorListener is configured as 'SENSOR_DELAY_FASTEST'). Please see [https://1drv.ms/v/s!AtC6mR0eG_AMawc4t0MtguIvmjw?e=3ddbzb](url) for the phenomenon. 

By contrast, the iPhone default compass APP (maybe the best compass APP I've used in market) almost never has such problems. I only tested the software on a Pixel 2XL phone (I have performed a few '8' for calibration but these issues still may occur).

My question is _if this is caused by insufficient calibration of the rotation sensor_, or _if it's related to the smartphone (and equipped sensor) model_? 

For now, my doubts for the above two issues are:

- **Jiggle of the heading**. This probably boils down to the sensor noise or similar. Perhaps a low pass filter on the azimuth outputs can smooth it?
- **Slow response of the heading**. I doubt if this is caused by inherent features of 'Sensor.TYPE_ROTATION_VECTOR', which is a software sensor based on sensor fusion between magnetometer, gyroscope and accelerometer. It can provide accurate results when being relatively stationary, but performs worse otherwise. Therefore, when the pose of phone changes fast there may be a delay for the azimuth to be stable. 

Potentially the above are something worth considering. Any ideas about the causes/solutions are appreciated!

**Comment by MrZMN** [comment]
Hi, I changed the sensor from 'Sensor.TYPE_ROTATION_VECTOR' to 'Sensor.TYPE_GEOMAGNETIC_ROTATION_VECTOR', which eliminates the use of gyroscope compared to the former counterpart.

Something interesting ensues after that. The jiggle problem becomes worse (if I put the phone on a flat table, it never stops jiggling in 1-2 degrees). By contrast, the slow response almost disappears. 

This confirms part of my previous assumptions, where we should blame the issues partly to the sensor fusion. I don't know  the internal realisation of the software sensors by Android (perhaps some Kalman Filters or AHRS), but I assume that there's always a tradeoff - one must sacrifice one thing to attain another thing. 

Any comments are appreciated.

**Comment by Kr0oked** [comment]
Hi, thanks for the nice words about the app!

With the current TYPE_ROTATION_VECTOR sensor the SDK takes care of everything. So the result is only as good as the implementation, your devices hardware and the factory calibration. I have seen big differences across my own test devices. Unfortunatly  I don't have many devices for testing.

When I started with the app I tried to filter the values myself [Older version](https://github.com/Kr0oked/Compass/commit/08554936c4f4d1b4b454ab87c3961579e98d3d62#diff-b3190b7091ed834162664849a958229a30f86ce45a14dd2e30b40bb5c35f9d00).
I used the TYPE_ACCELEROMETER and TYPE_MAGNETIC_FIELD in combination with a low pass filter. I also tried out some more filtering to improve the result. But it was either unstable or unresponsive. As you said there is always a tradeoff. So I gave up this approach and I now rely on the TYPE_ROTATION_VECTOR which produces a better result then I can do.

If you want to experiment a little bit more and try out your own filtering you can now have a look at uncalibrated filters like [TYPE_MAGNETIC_FIELD_UNCALIBRATED](https://developer.android.com/guide/topics/sensors/sensors_position#sensors-pos-magunc):

> Note: Uncalibrated sensors provide more raw results and may include some bias, but their measurements contain fewer jumps from corrections applied through calibration. Some applications may prefer these uncalibrated results as smoother and more reliable. For instance, if an application is attempting to conduct its own sensor fusion, introducing calibrations can actually distort results.

**Comment by MrZMN** [comment]
Thank you for the reply! The information you provided is absolutely helpful! I agree that the result should rely on the specific devices. 

I agree that it's wise to use Android SDK methods, although it's not likely that they'll bring about superb performance on each individual device (not like Apple who only has a few phone models). Maybe implementing the whole thing from scratch can potentially have somewhat better performance, but I doubt it requires much effort.

Again, thank you for your excellent contribution!
