### ISSUE TITLE
APK in releases

### ISSUE THREAD

**Issue by loopdeeloop** [Kr0oked/Compass#34]
Hello, could you please provide the APK file for new releases?

**Comment by Kr0oked** [comment]
Hi, you can download the latest APKs from the F-Droid Website: https://f-droid.org/de/packages/com.bobek.compass/
I hope that is sufficient for now. You can then also be sure that you get an APK that is build only with the stuff from this repository and is not modified in any other way.

**Comment by m0byn** [comment]
I would actually vote for providing the APK file in the releases...I use obtainium to update my apps and prefer to directly access and update my applications through github. If that was possible I would highly appreciate it :)
