### ISSUE TITLE
GPS coordinates

### ISSUE THREAD

**Issue by bonneval** [Kr0oked/Compass#4]
Hello,

can you please show the GPS coordinates and the altitude on the main screen.

Would be really helpful in some cases.

Thanks a lot!

**Comment by Kr0oked** [comment]
At the moment GPS functionalities are out of the applications scope.
I can recomment the app [Trail-Sense](https://github.com/kylecorry31/Trail-Sense) which includes these and other functionalities that go beyond a simple compass.
