### ISSUE TITLE
Option to change color of the app icon

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#50]

**Comment by Kr0oked** [comment]
As far as I know is it not possible to change the app icon dynamically. But also I want to stick to the Android app standards with their [Adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive). So the icon already adapts to the user theme. Maybe Android allows more customization out of the box in future versions.

**Comment by inson1** [comment]
@Kr0oked It is possible, 
Simple mobile apps do that for example 
This could be default color and then user could change it
