### ISSUE TITLE
Align Ok button on default error pop up to center

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#51]
I think it would look nicer.

![Screenshot_2023-10-16-06-33-26-115_com.bobek.compass.jpg](https://github.com/Kr0oked/Compass/assets/75314629/407e41ce-7eaf-4953-8cc7-ece658e39279)

**Comment by Kr0oked** [comment]
I think it would look odd to have the button centered. Its also not a default option when using [Dialogs](https://m2.material.io/components/dialogs/android#using-dialogs). But I have seen that it is more common to have the OK button as a "positive" button that gets aligned to to the right and is therefore better reachable for users.

**Comment by inson1** [comment]
@Kr0oked Right side? I agree. 

Btw I said center, because there arent any other options.
