### ISSUE TITLE
Add option to settings to change the language of the app

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#54]

**Comment by Kr0oked** [comment]
The app already supports the per-app language settings of Android 13. See [Per-app language preferences](https://developer.android.com/guide/topics/resources/app-languages). So I think there is no need for an additional setting in the app itself.

PS @inson1 : Thanks for all the input, it is still highly appreciated. I will go through all of your issues each when I find the time.

**Comment by inson1** [comment]
@Kr0oked Yea I dont have Android 13 yet, so I didnt know that. Btw great job with the links. Maybe add it into features section? But I would still prefer to have this option in the app imho.

Yea, I get it. Thank you for you work!

**Comment by inson1** [comment]
"Maybe add it into features section?"

@Kr0oked  Well I going to create for that another issue. #58
