### ISSUE TITLE
Github, not Git Hub

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#56]
![IMG_20231016_080110.jpg](https://github.com/Kr0oked/Compass/assets/75314629/de9f4b69-33fd-45b0-8205-bd9fc415a181)

**Comment by Kr0oked** [comment]
Already fixed in https://github.com/Kr0oked/Compass/pull/48 . Should be fixed in the next release.

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
