### ISSUE TITLE
Add a language 

### ISSUE THREAD

**Issue by Maha-Rajan** [Kr0oked/Compass#68]
Hello I would Like to contribute to translation in my native language. How can I add my own transactions? Still understanding GitHub so a bit confused

**Comment by inson1** [comment]
@Maha-Rajan What language? and What language code?
Is here https://github.com/Kr0oked/Compass?tab=readme-ov-file#translations ?


You have to create pull request with changes

https://github.com/Kr0oked/Compass/tree/master/fastlane/metadata/android
https://github.com/Kr0oked/Compass/tree/master/app/src/main/res

**Comment by Maha-Rajan** [comment]
The language is Tamil(ta). It has 90M native speakers. I thought there might be something like a crowdin or other language translation service from which I could contribute as I'm not much familiar with using GitHub. But, I'll try to add it the way you have advised.

**Comment by inson1** [comment]
@Maha-Rajan not yet https://github.com/Kr0oked/Compass/issues/55

**Comment by inson1** [comment]
@Maha-Rajan btw if you like the idea (about translation platform) go give it like

**Comment by Kr0oked** [comment]
@Maha-Rajan Thanks for offering a translation. I think the easist solution would be if you just download these files and translate the contained texts. There is a download button in the upper right when viewing a file.
Then attach the translated files here in the chat I will take care of the rest.

https://github.com/Kr0oked/Compass/blob/master/app/src/main/res/values/strings.xml
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/title.txt
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/short_description.txt
https://github.com/Kr0oked/Compass/blob/master/fastlane/metadata/android/en-US/full_description.txt

**Comment by Maha-Rajan** [comment]
GitHub does not seem to allow .xml uploading so I have sent the files by mail

**Comment by Maha-Rajan** [comment]
let me know if the files are ok so that i can close the commit

**Comment by Kr0oked** [comment]
@Maha-Rajan The files were ok. I added the implementation in the latest commit https://github.com/Kr0oked/Compass/commit/1772a9db475e61be1fb4656e00a0513e71646fd1 . So the translation willl be included in the next release.

Thanks a log for your effort!
