### ISSUE TITLE
Change repository details Description 

### ISSUE THREAD

**Issue by inson1** [Kr0oked/Compass#70]
to your fastlane short_description.txt text plus that it is for Android  "Simple and beautiful compass for Android."

I think it looks better

**Comment by Kr0oked** [comment]
When you are browsing apps in F-Droid or Google Play then I think its already obvious that the app is for Anroid, so I'll keep the current text :sweat_smile:

**Comment by inson1** [comment]
@Kr0oked I meant here on Github. Under About.

**Comment by Kr0oked** [comment]
Alright thanks for the clarification, changed it :+1:
