### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by Edygard0** [Kr0oked/Compass#76]
Hello,
   Attached (string-es.zip) you'll find the spanish translation for Compass. Hope it can be included in the next release.

Regards
Edgardo

[strings-es.zip](https://github.com/Kr0oked/Compass/files/14621999/strings-es.zip)

**Comment by Kr0oked** [comment]
Hi Edgardo,

thanks a lot for the translation. The strings.xml look good.
Could you also provide a translation for the title.txt, short_description.txt and full_description.txt in fastlane/metadata/android/en-US ? These are the texts used in the app stores. Posting the translation in a comment should be enough.

Thanks in advance,
Philipp

**Comment by Edygard0** [comment]
Hi Philippp:
    No problem, attached you'll find the three files translated.

Edgardo

[fastlane-es.zip](https://github.com/Kr0oked/Compass/files/14625537/fastlane-es.zip)

**Comment by Kr0oked** [comment]
Thanks again. I added your translations in the latest commit https://github.com/Kr0oked/Compass/commit/f883c70122fa739714bb52f07cdcbb04e5c77144
