### ISSUE TITLE
[Feature] Add Level

### ISSUE THREAD

**Issue by newhinton** [Kr0oked/Compass#78]
Woulf you be willing to also add a "level" indicator to this app? Sometimes it would be nice to also see the device's orientation in relation to gravity.

This could be added on a second "page" accessible by a bottom bar.

I'd also be willing to try to implement this and create a PR if you like.

Sorry for the premature posting.

**Comment by Kr0oked** [comment]
Hi, sorry for the moment I don't want to include a level tool in the app. But thanks for offering help.
Actually this feature was requested a few times.

But I want to explain my decission a little bit. I think you dont need a level tool for a compass app. And a compass functionality is the only thing the app wants to offer.
Traditional compasses needed to be leveled to function correctly. But an app compensates that and you dont have to care about the device leveling when using the app.

**Comment by newhinton** [comment]
> And a compass functionality is the only thing the app wants to offer.

I thought so much already, but i wanted to ask nonetheless.

> Traditional compasses needed to be leveled to function correctly.

My reasoning was actually not about the compass at all. If i want to hang a picture or something else, i have to also have a different app. With an integrated level i'd only need one app. But i definitively see and respect your choice to not add that feature.

Also sorry for not finding the other level-requests. I assume they are the magnetic field strength ones, i didnt search for that initially.

**Comment by Kr0oked** [comment]
No problem at all. Could be the case that I just got direct messages with that feature request.

There is actually a use case that needs both a compass and a level tool. The alignment of solar panel. There you want to align it to a specific direction and level.

But I think this is a really specific use case that should have a dedicated app.
