### ISSUE TITLE
Danish translation

### ISSUE THREAD

**Issue by kascvid** [Kr0oked/Compass#80]
Hi,

I just translated the software to danish (dk) including the meta texts. Unfortuantly I had to change the file extension for strings-dk in order to add the file here directly.

[strings-dk.txt](https://github.com/Kr0oked/Compass/files/14883036/strings-dk.txt)

[full_description.txt](https://github.com/Kr0oked/Compass/files/14882966/full_description.txt)

[short_description.txt](https://github.com/Kr0oked/Compass/files/14882957/short_description.txt)

[title.txt](https://github.com/Kr0oked/Compass/files/14882975/title.txt)

**Comment by Kr0oked** [comment]
Hi,
thanks a lot for the translation! I added your files in the referenced commit. I put the translation in the `da` directory. I think that is correct for Danish.
