### ISSUE TITLE
Signing Key seems to have change with 1.14.2

### ISSUE THREAD

**Issue by rusty-snake** [Kr0oked/Compass#87]
Signing Key seems to have change with 1.14.2.

Any comment/reason and validation of trust?

**Comment by Kr0oked** [comment]
I am currently reworking the deployment of the app. Are you referring to the attached APK of the GitHub release?

* The latest Google Playstore version should still have the same valid signing.
* The upcoming F-Droid version gets build by F-Droid itself and should also stay valid
* Just the attached APK in the GitHub release is now unsigned, it was previously signed with the same key as the Google Playstore releases. But I am not sure if I will continue to sign these APKs with this key or if I will discontinue the attached APKs completely

I recommend to use one of the playstores to receive the app.
Sorry for the unanounced inconvenience.

**Comment by DiagonalArg** [comment]
@Kr0oked / Please don't dispense with the .apk's on github.  Many of us, particularly those on [GrapheneOS](https://grapheneos.org/), use [Obtainium](https://github.com/ImranR98/Obtainium) along with [AppVerifier](https://github.com/soupslurpr/AppVerifier) to grab our apk's, signed by the dev, from github.  F-droid's security model is poor, and it's because I use this system that I was alerted that your signing key had changed.

**Comment by boredsquirrel** [comment]
same here. F-Droid delays updates, you sign the APKs before pushing to Google Play, right? I would also appreciate to still push them to the releases too, especially as the Android Packagemanager works reliably and securely (aka currently installs dont work)

Google Play is a walled garden and does not work with alternative, less invasive, smaller, more secure clients like Obtainium.

Thanks for this great app btw.

**Comment by Kr0oked** [comment]
Alright, in that case I will continue to provide signed APKs for you in the GitHub releases.
I want to support all users that don't want to bind themself to Google services. I thought that all of you receive their apps with F-Droid and my attached APKs are only used when somebody does not want to wait until F-Droid caught up with building the latest version.

I updated the latest release with a signed `app-release.apk` attachment.
