### ISSUE TITLE
Feature request: True dark mode

### ISSUE THREAD

**Issue by Hund** [Kr0oked/Compass#88]
It would be nice if we could have true dark mode, with a black (#000) background. This would be more battery efficient on phones with AMOLED-displays.

**Comment by Kr0oked** [comment]
I'm sorry to decline the request. Currently I don't want to maintain additional themes for the app. I will stick to the Adnroid standard (day/night themes). Maybe a future Android version introduces a standard to support the capabilities of AMOLED displays better.

**Comment by Hund** [comment]
I completely understand. :)
