### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [Kr0oked/Compass#96]
I want to use your compass in my application, how do I do it? Is there documentation?

**Comment by Kr0oked** [comment]
Hi, unfortunately this compass is not designed as a library or plugin that can be reused in other applications.
The only thing that you can do right now is to have a look at the individual source files of this app and try to reuse them in your app.

The functionality is split in a compass view in https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/view/CompassView.kt and https://github.com/Kr0oked/Compass/blob/master/app/src/main/res/layout/compass_view.xml . It's purpose is to display the compass in the UI.
And then there is the fragment  https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/CompassFragment.kt that is there to coordinate all of the app logic, calculate the compass direction and pass it on to the view.

Please keep in mind that you have to comply to the GPLv3 license if you reuse any code https://github.com/Kr0oked/Compass/blob/master/LICENSE .

**Comment by hasanelfalakiy** [comment]
> Hi, unfortunately this compass is not designed as a library or plugin that can be reused in other applications.
> The only thing that you can do right now is to have a look at the individual source files of this app and try to reuse them in your app.
> 
> The functionality is split in a compass view in https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/view/CompassView.kt and https://github.com/Kr0oked/Compass/blob/master/app/src/main/res/layout/compass_view.xml . It's purpose is to display the compass in the UI.
> And then there is the fragment  https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/CompassFragment.kt that is there to coordinate all of the app logic, calculate the compass direction and pass it on to the view.
> 
> Please keep in mind that you have to comply to the GPLv3 license if you reuse any code https://github.com/Kr0oked/Compass/blob/master/LICENSE .

oh okay

**Comment by hasanelfalakiy** [comment]
> Hi, unfortunately this compass is not designed as a library or plugin that can be reused in other applications. The only thing that you can do right now is to have a look at the individual source files of this app and try to reuse them in your app.
> 
> The functionality is split in a compass view in https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/view/CompassView.kt and https://github.com/Kr0oked/Compass/blob/master/app/src/main/res/layout/compass_view.xml . It's purpose is to display the compass in the UI. And then there is the fragment https://github.com/Kr0oked/Compass/blob/master/app/src/main/java/com/bobek/compass/CompassFragment.kt that is there to coordinate all of the app logic, calculate the compass direction and pass it on to the view.
> 
> Please keep in mind that you have to comply to the GPLv3 license if you reuse any code https://github.com/Kr0oked/Compass/blob/master/LICENSE .

![Screenshot_20240920_101916](https://github.com/user-attachments/assets/4df5bc4d-1d08-450a-9e4d-2e325e06ba1d)

does that mean i also have to use all the files needed in this fragment?
then if i use your code file what are the terms, what should i do regarding this license rules?

**Comment by Kr0oked** [comment]
You can modify the file to your needs or copy parts of it. 
But then you have to leave a notice that you put the code from this repository. And you have to include the license text and a copyright notice in all distributions. Maybe this explanation helps: https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60#file-gplv3-md


I don't know what your app is about and how you want to use my code. But it is probably best if you just use my code to study it and learn how it works and then come up with your own implementation. Without any copy pasting. Then you don't have to deal with the licensing.

**Comment by hasanelfalakiy** [comment]
> You can modify the file to your needs or copy parts of it. 
> But then you have to leave a notice that you put the code from this repository. And you have to include the license text and a copyright notice in all distributions. Maybe this explanation helps: https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60#file-gplv3-md
> 
> 
> I don't know what your app is about and how you want to use my code. But it is probably best if you just use my code to study it and learn how it works and then come up with your own implementation. Without any copy pasting. Then you don't have to deal with the licensing.

oh okay I see
